name: 'Setup QMK firmware'

inputs:
  version:
    default: '0.16.3'
    type: string
    required: false
  path:
    default: '__qmk__'
    type: string
    required: false

runs:
  using: 'composite'
  steps:
  - name: Checkout qmk_firmware
    uses: actions/checkout@v3
    with:
      path: ${{ inputs.path }}
      repository: qmk/qmk_firmware
      submodules: recursive
      ref: ${{ inputs.version }}

  - name: Install git and pip
    shell: bash
    run: sudo apt-get install -y git python3-pip

  - name: Install QMK CLI
    shell: bash
    run: python3 -m pip install --user qmk

  - name: Setup QMK
    shell: bash
    run: qmk setup --home ${{ inputs.path }} --yes
